### PR TITLE
[misc]: Initial repository setup.

### PR DESCRIPTION
**Pull request by ss-o**

### CODE REVIEW

**Comment by ss-o** [comment]
@0xMRTT,

It's the initial setup, but if have suggestions - welcome.

**Review by 0xMRTT — CHANGES_REQUESTED** [review]
Add ability to chose the prefix by setting $_ZO_CMD_PREFIX in .zshrc. So user can customize the prefix before initializing zoxide

**Review by 0xMRTT — APPROVED** [review]
Just need to add this possibility in the wiki. But all seems to be good 😁

**Comment by ss-o** [comment]
> Just need to add this possibility in the wiki. But all seems to be good grin

I thought you did already :octocat:

**Review by 0xMRTT — APPROVED** [review]
Great. I think that we can also add this in zoxise repo. In the table at the end of the READ ME?

**Comment by ss-o** [comment]
> Great. I think that we can also add this in zoxise repo. In the table at the end of the READ ME?

No, it needs more work, it's the initial setup, needs to test, try end, etc.

**Comment by 0xMRTT** [comment]
Work perfetcly on my side, with turbo mode and for syntax

**Comment by ss-o** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
To build on this closed PR, you can clone it using this method:
  - https://stackoverflow.com/a/14969986
Then open a new PR, referencing this closed PR in your message.

**Pull request merged**
